CREATE TABLE TUsers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL
);

INSERT INTO TUsers (login, email) VALUES ('user1', 'user1@mail.com');
INSERT INTO TUsers (login, email) VALUES ('user2', 'user2@mail.com');
INSERT INTO TUsers (login, email) VALUES ('user3', 'user3@mail.com');

SELECT id, login, email FROM TUsers;
