package Connection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class DBConnection {

	public static void main(String[] args) {
		String jdbcUrl = "jdbc:oracle:thin:@//localhost:1521/xe";
        String username = "SYS AS SYSDBA";
        String password = "man8ix";

        try (Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
            if (connection != null) {
                System.out.println("Connection is success!");
                
                String createTableSQL = "CREATE TABLE users (" +
                        "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "login VARCHAR2(50) NOT NULL, " +
                        "password VARCHAR2(50) NOT NULL)";
                
                try (Statement stmt = connection.createStatement()) {
                    stmt.executeUpdate(createTableSQL);
                    System.out.println("The tables users has been created.");
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
                
                String insertSQL = "INSERT INTO users (login, password) VALUES (?, ?)";
                
                try (PreparedStatement pstmt = connection.prepareStatement(insertSQL)) {
                    pstmt.setString(1, "user1");
                    pstmt.setString(2, "password123");
                    pstmt.addBatch();
                    
                    pstmt.setString(1, "user2");
                    pstmt.setString(2, "password456");
                    pstmt.addBatch();
                    
                    pstmt.setString(1, "user3");
                    pstmt.setString(2, "password789");
                    pstmt.addBatch();

                    int[] results = pstmt.executeBatch();
                    
                    int insertedCount = 0;
                    for (int result : results) {
                        if (result != Statement.EXECUTE_FAILED) {
                            insertedCount++;
                        }
                    }
                    System.out.println("Rows added: " + insertedCount);
                }

            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
	}

}
